name: Print Txt file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  read_my_file:
    runs-on: ubuntu-latest
    steps:
      - name: Git repo checkout koro (checkout maane clone kora)
        uses: actions/checkout@v2
      - name: Read the txt file
        run: cat hello.txt
