name: Print Txt file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  read_my_file:
    runs-on: self-hosted
    steps:
      - name: Git repo checkout korun mane clone korun
        uses: actions/checkout@v2
      - name: Read the txt file
        run: |
          ls -l
